{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mee6k-box.fullname" . }}-api-gateway
  labels:
    {{- include "mee6k-box.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mee6k-box.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}