{{- if .Values.runtimeGuardian.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mee6k-box.fullname" . }}-runtime-guardian
  labels:
    {{- include "mee6k-box.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime-guardian
spec:
  type: {{ .Values.runtimeGuardian.service.type }}
  ports:
    - port: {{ .Values.runtimeGuardian.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mee6k-box.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: runtime-guardian
{{- end }}